# -*- coding: utf-8 -*-
"""DataFrameWin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kg0PJystxTYnJY4tRrBt0ERk3d7_-dXs
"""

import pandas as pd
base = pd.read_csv('/home/Dados_Hist_WIN$N_30.csv', sep=";")
base.head()

base.shape

X = base.iloc[:, 1:-1]
y = base.iloc[:, -1]

# Separa os dados para treinamento e teste
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.2, random_state=2)
X_treinamento.shape

X_teste.shape

# Treinamento
from sklearn.linear_model import LogisticRegression
classificador = LogisticRegression(max_iter = 30)
classificador.fit(X_treinamento, y_treinamento)

# Teste
previsoes = classificador.predict(X_teste)

from sklearn.metrics import accuracy_score
taxa_acerto = accuracy_score(y_teste, previsoes)

# Exemplo: 0.87 significa 87% de acerto.
taxa_acerto